Fix prism_spot_def_for_name for singletons
Previously calling a singleton method with invalid arguments would give:

    RuntimeError: Incompatible locations

This is because `join` wants the operator to come before the location